
image: kanuahs93/flask-sample-app
replicaCount: 10

service:
  portName: flask-port
  type: LoadBalancer
  internalPort: 5000
  externalPort: 5000

ingress:
  enabled: True
  annotations:
    http.port: "5000"
  hosts: 
    - testhost
